<?php

/*
 * PHPSure
 * Copyright (c) Dan Phillimore (asmblah)
 * https://github.com/phpsure/phpsure/
 *
 * Released under the MIT license.
 * https://github.com/phpsure/phpsure/raw/main/MIT-LICENSE.txt
 */

declare(strict_types=1);

namespace PHPSure\Tests\Unit\Runner;

use Mockery\MockInterface;
use PHPSure\Discovery\DiscoveryResultInterface;
use PHPSure\Runner\ClassMemberTesterInterface;
use PHPSure\Runner\ClassTester;
use PHPSure\Runner\InstanceCreatorInterface;
use PHPSure\Runner\Result\SkipResult;
use PHPSure\Tests\AbstractTestCase;
use RuntimeException;

/**
 * Class ClassTesterTest.
 *
 * @author Dan Phillimore <dan@ovms.co>
 */
class ClassTesterTest extends AbstractTestCase
{
    private MockInterface&ClassMemberTesterInterface $classMemberTester;
    private ClassTester $classTester;
    private MockInterface&DiscoveryResultInterface $discoveryResult;
    private MockInterface&InstanceCreatorInterface $instanceCreator;

    public function setUp(): void
    {
        $this->instanceCreator = mock(InstanceCreatorInterface::class);
        $this->classMemberTester = mock(ClassMemberTesterInterface::class);
        $this->discoveryResult = mock(DiscoveryResultInterface::class);

        $this->classTester = new ClassTester(
            $this->instanceCreator,
            $this->classMemberTester
        );
    }

    public function testTestClassesCreatesInstanceAndTestsInstanceAndStaticMethods(): void
    {
        $passes = [];
        $failures = [];
        $skips = [];
        $warnings = [];
        $instance = new \stdClass();

        $this->discoveryResult->allows('getClassNames')
            ->andReturn(['stdClass']);

        $this->instanceCreator->expects('createInstance')
            ->once()
            ->with('stdClass', \Mockery::on(function (&$wasAutoGenerated) {
                $wasAutoGenerated = false;
                return true;
            }))
            ->andReturn($instance);

        $this->classMemberTester->expects('testInstanceMethods')
            ->once()
            ->with('stdClass', $instance, false, [], [], [], []);

        $this->classMemberTester->expects('testStaticMethods')
            ->once()
            ->with('stdClass', [], [], [], []);

        $this->classTester->testClasses(
            $this->discoveryResult,
            $passes,
            $failures,
            $skips,
            $warnings
        );
    }

    public function testTestClassesSkipsAbstractClasses(): void
    {
        $passes = [];
        $failures = [];
        $skips = [];
        $warnings = [];

        $this->discoveryResult->allows('getClassNames')
            ->andReturn([ClassTesterTestAbstractClass::class]);

        $this->instanceCreator->expects('createInstance')
            ->never();

        $this->classMemberTester->expects('testInstanceMethods')
            ->never();

        $this->classMemberTester->expects('testStaticMethods')
            ->never();

        $this->classTester->testClasses(
            $this->discoveryResult,
            $passes,
            $failures,
            $skips,
            $warnings
        );

        $this->assertCount(0, $passes);
        $this->assertCount(0, $failures);
        $this->assertCount(0, $skips);
        $this->assertCount(0, $warnings);
    }

    public function testTestClassesSkipsInterfaces(): void
    {
        $passes = [];
        $failures = [];
        $skips = [];
        $warnings = [];

        $this->discoveryResult->allows('getClassNames')
            ->andReturn([ClassTesterTestInterface::class]);

        $this->instanceCreator->expects('createInstance')
            ->never();

        $this->classMemberTester->expects('testInstanceMethods')
            ->never();

        $this->classMemberTester->expects('testStaticMethods')
            ->never();

        $this->classTester->testClasses(
            $this->discoveryResult,
            $passes,
            $failures,
            $skips,
            $warnings
        );

        $this->assertCount(0, $passes);
        $this->assertCount(0, $failures);
        $this->assertCount(0, $skips);
        $this->assertCount(0, $warnings);
    }

    public function testTestClassesAddsSkipResultWhenExceptionIsThrownDuringClassProcessing(): void
    {
        $passes = [];
        $failures = [];
        $skips = [];
        $warnings = [];

        $this->discoveryResult->allows('getClassNames')
            ->andReturn(['stdClass']);

        $this->instanceCreator->allows('createInstance')
            ->andThrow(new RuntimeException('Cannot create instance'));

        $this->classMemberTester->expects('testInstanceMethods')
            ->never();

        $this->classMemberTester->expects('testStaticMethods')
            ->never();

        $this->classTester->testClasses(
            $this->discoveryResult,
            $passes,
            $failures,
            $skips,
            $warnings
        );

        $this->assertCount(0, $passes);
        $this->assertCount(0, $failures);
        $this->assertCount(1, $skips);
        $this->assertInstanceOf(SkipResult::class, $skips[0]);
        $this->assertSame('Class stdClass', $skips[0]->identifier);
        $this->assertSame('Cannot create instance', $skips[0]->message);
        $this->assertCount(0, $warnings);
    }

    public function testTestClassesPassesAutoGeneratedFlagToClassMemberTester(): void
    {
        $passes = [];
        $failures = [];
        $skips = [];
        $warnings = [];
        $instance = new \stdClass();

        $this->discoveryResult->allows('getClassNames')
            ->andReturn(['stdClass']);

        $this->instanceCreator->allows('createInstance')
            ->andReturnUsing(function ($className, &$wasAutoGenerated) use ($instance) {
                $wasAutoGenerated = true;
                return $instance;
            });

        $this->classMemberTester->expects('testInstanceMethods')
            ->once()
            ->with('stdClass', $instance, true, [], [], [], []);

        $this->classMemberTester->allows('testStaticMethods');

        $this->classTester->testClasses(
            $this->discoveryResult,
            $passes,
            $failures,
            $skips,
            $warnings
        );
    }

    public function testTestClassesHandlesNullInstanceFromInstanceCreator(): void
    {
        $passes = [];
        $failures = [];
        $skips = [];
        $warnings = [];

        $this->discoveryResult->allows('getClassNames')
            ->andReturn(['stdClass']);

        $this->instanceCreator->allows('createInstance')
            ->andReturnUsing(function ($className, &$wasAutoGenerated) {
                $wasAutoGenerated = false;
                return null;
            });

        $this->classMemberTester->expects('testInstanceMethods')
            ->once()
            ->with('stdClass', null, false, [], [], [], []);

        $this->classMemberTester->expects('testStaticMethods')
            ->once()
            ->with('stdClass', [], [], [], []);

        $this->classTester->testClasses(
            $this->discoveryResult,
            $passes,
            $failures,
            $skips,
            $warnings
        );
    }

    public function testTestClassesHandlesMultipleClasses(): void
    {
        $passes = [];
        $failures = [];
        $skips = [];
        $warnings = [];
        $instance1 = new \stdClass();
        $instance2 = new \stdClass();

        $this->discoveryResult->allows('getClassNames')
            ->andReturn(['stdClass', 'ArrayObject']);

        $this->instanceCreator->allows('createInstance')
            ->andReturnUsing(function ($className, &$wasAutoGenerated) use ($instance1, $instance2) {
                $wasAutoGenerated = false;
                return $className === 'stdClass' ? $instance1 : $instance2;
            });

        $this->classMemberTester->expects('testInstanceMethods')
            ->once()
            ->with('stdClass', $instance1, false, [], [], [], []);

        $this->classMemberTester->expects('testInstanceMethods')
            ->once()
            ->with('ArrayObject', $instance2, false, [], [], [], []);

        $this->classMemberTester->expects('testStaticMethods')
            ->once()
            ->with('stdClass', [], [], [], []);

        $this->classMemberTester->expects('testStaticMethods')
            ->once()
            ->with('ArrayObject', [], [], [], []);

        $this->classTester->testClasses(
            $this->discoveryResult,
            $passes,
            $failures,
            $skips,
            $warnings
        );
    }
}

abstract class ClassTesterTestAbstractClass
{
    abstract public function myMethod(): void;
}

interface ClassTesterTestInterface
{
    public function myMethod(): void;
}
