<?php

/*
 * PHPSure
 * Copyright (c) Dan Phillimore (asmblah)
 * https://github.com/phpsure/phpsure/
 *
 * Released under the MIT license.
 * https://github.com/phpsure/phpsure/raw/main/MIT-LICENSE.txt
 */

declare(strict_types=1);

namespace PHPSure\Tests\Unit\Runner;

use Mockery\MockInterface;
use PHPSure\Discovery\Scanner;
use PHPSure\Generator\TokenGenerator;
use PHPSure\Runner\ClassMemberTester;
use PHPSure\Runner\MethodTesterInterface;
use PHPSure\Tests\AbstractTestCase;
use ReflectionMethod;

/**
 * Class ClassMemberTesterTest.
 *
 * @author Dan Phillimore <dan@ovms.co>
 */
class ClassMemberTesterTest extends AbstractTestCase
{
    private ClassMemberTester $classMemberTester;
    private MockInterface&MethodTesterInterface $methodTester;
    private MockInterface&Scanner $scanner;
    private MockInterface&TokenGenerator $tokenGenerator;

    public function setUp(): void
    {
        $this->scanner = mock(Scanner::class);
        $this->tokenGenerator = mock(TokenGenerator::class);
        $this->methodTester = mock(MethodTesterInterface::class);

        $this->classMemberTester = new ClassMemberTester(
            $this->scanner,
            $this->tokenGenerator,
            $this->methodTester
        );
    }

    public function testTestInstanceMethodsCallsMethodTesterForEachInstanceMethod(): void
    {
        $passes = [];
        $failures = [];
        $skips = [];
        $warnings = [];
        $instance = new ClassMemberTesterTestClass();
        $method1 = new ReflectionMethod(ClassMemberTesterTestClass::class, 'instanceMethod1');
        $method2 = new ReflectionMethod(ClassMemberTesterTestClass::class, 'instanceMethod2');

        $this->scanner->expects('getInstanceMethods')
            ->once()
            ->with(ClassMemberTesterTestClass::class)
            ->andReturn([
                'instanceMethod1' => $method1,
                'instanceMethod2' => $method2,
            ]);

        $this->tokenGenerator->allows('generateForParameters')
            ->andReturn([]);

        $this->methodTester->expects('testInstanceMethod')
            ->once()
            ->with(
                ClassMemberTesterTestClass::class,
                'instanceMethod1',
                $method1,
                \Mockery::type('callable'),
                $instance,
                false,
                [],
                [],
                [],
                []
            );

        $this->methodTester->expects('testInstanceMethod')
            ->once()
            ->with(
                ClassMemberTesterTestClass::class,
                'instanceMethod2',
                $method2,
                \Mockery::type('callable'),
                $instance,
                false,
                [],
                [],
                [],
                []
            );

        $this->classMemberTester->testInstanceMethods(
            ClassMemberTesterTestClass::class,
            $instance,
            false,
            $passes,
            $failures,
            $skips,
            $warnings
        );
    }

    public function testTestInstanceMethodsPassesAutoGeneratedFlagToMethodTester(): void
    {
        $passes = [];
        $failures = [];
        $skips = [];
        $warnings = [];
        $instance = new ClassMemberTesterTestClass();
        $method = new ReflectionMethod(ClassMemberTesterTestClass::class, 'instanceMethod1');

        $this->scanner->allows('getInstanceMethods')
            ->andReturn(['instanceMethod1' => $method]);

        $this->tokenGenerator->allows('generateForParameters')
            ->andReturn([]);

        $this->methodTester->expects('testInstanceMethod')
            ->once()
            ->with(
                ClassMemberTesterTestClass::class,
                'instanceMethod1',
                $method,
                \Mockery::type('callable'),
                $instance,
                true,
                [],
                [],
                [],
                []
            );

        $this->classMemberTester->testInstanceMethods(
            ClassMemberTesterTestClass::class,
            $instance,
            true,
            $passes,
            $failures,
            $skips,
            $warnings
        );
    }

    public function testTestInstanceMethodsHandlesNullInstance(): void
    {
        $passes = [];
        $failures = [];
        $skips = [];
        $warnings = [];
        $method = new ReflectionMethod(ClassMemberTesterTestClass::class, 'instanceMethod1');

        $this->scanner->allows('getInstanceMethods')
            ->andReturn(['instanceMethod1' => $method]);

        $this->tokenGenerator->allows('generateForParameters')
            ->andReturn([]);

        $this->methodTester->expects('testInstanceMethod')
            ->once()
            ->with(
                ClassMemberTesterTestClass::class,
                'instanceMethod1',
                $method,
                \Mockery::type('callable'),
                null,
                false,
                [],
                [],
                [],
                []
            );

        $this->classMemberTester->testInstanceMethods(
            ClassMemberTesterTestClass::class,
            null,
            false,
            $passes,
            $failures,
            $skips,
            $warnings
        );
    }

    public function testTestInstanceMethodsPassesInvokerCallableToMethodTester(): void
    {
        $passes = [];
        $failures = [];
        $skips = [];
        $warnings = [];
        $instance = new ClassMemberTesterTestClass();
        $method = new ReflectionMethod(ClassMemberTesterTestClass::class, 'instanceMethod1');

        $this->scanner->allows('getInstanceMethods')
            ->andReturn(['instanceMethod1' => $method]);

        $this->tokenGenerator->allows('generateForParameters')
            ->andReturn([]);

        $this->methodTester->expects('testInstanceMethod')
            ->once()
            ->with(
                ClassMemberTesterTestClass::class,
                'instanceMethod1',
                $method,
                \Mockery::type('callable'),
                $instance,
                false,
                [],
                [],
                [],
                []
            );

        $this->classMemberTester->testInstanceMethods(
            ClassMemberTesterTestClass::class,
            $instance,
            false,
            $passes,
            $failures,
            $skips,
            $warnings
        );
    }

    public function testTestStaticMethodsCallsMethodTesterForEachStaticMethod(): void
    {
        $passes = [];
        $failures = [];
        $skips = [];
        $warnings = [];
        $method1 = new ReflectionMethod(ClassMemberTesterTestClass::class, 'staticMethod1');
        $method2 = new ReflectionMethod(ClassMemberTesterTestClass::class, 'staticMethod2');

        $this->scanner->expects('getStaticMethods')
            ->once()
            ->with(ClassMemberTesterTestClass::class)
            ->andReturn([
                'staticMethod1' => $method1,
                'staticMethod2' => $method2,
            ]);

        $this->tokenGenerator->allows('generateForParameters')
            ->andReturn([]);

        $this->methodTester->expects('testStaticMethod')
            ->once()
            ->with(
                ClassMemberTesterTestClass::class,
                'staticMethod1',
                $method1,
                \Mockery::type('callable'),
                [],
                [],
                [],
                []
            );

        $this->methodTester->expects('testStaticMethod')
            ->once()
            ->with(
                ClassMemberTesterTestClass::class,
                'staticMethod2',
                $method2,
                \Mockery::type('callable'),
                [],
                [],
                [],
                []
            );

        $this->classMemberTester->testStaticMethods(
            ClassMemberTesterTestClass::class,
            $passes,
            $failures,
            $skips,
            $warnings
        );
    }

    public function testTestStaticMethodsPassesInvokerCallableToMethodTester(): void
    {
        $passes = [];
        $failures = [];
        $skips = [];
        $warnings = [];
        $method = new ReflectionMethod(ClassMemberTesterTestClass::class, 'staticMethod1');

        $this->scanner->allows('getStaticMethods')
            ->andReturn(['staticMethod1' => $method]);

        $this->tokenGenerator->allows('generateForParameters')
            ->andReturn([]);

        $this->methodTester->expects('testStaticMethod')
            ->once()
            ->with(
                ClassMemberTesterTestClass::class,
                'staticMethod1',
                $method,
                \Mockery::type('callable'),
                [],
                [],
                [],
                []
            );

        $this->classMemberTester->testStaticMethods(
            ClassMemberTesterTestClass::class,
            $passes,
            $failures,
            $skips,
            $warnings
        );
    }

    public function testTestStaticMethodsPassesNullAsInstanceToMethodTester(): void
    {
        $passes = [];
        $failures = [];
        $skips = [];
        $warnings = [];
        $method = new ReflectionMethod(ClassMemberTesterTestClass::class, 'staticMethod1');

        $this->scanner->allows('getStaticMethods')
            ->andReturn(['staticMethod1' => $method]);

        $this->tokenGenerator->allows('generateForParameters')
            ->andReturn([]);

        $this->methodTester->expects('testStaticMethod')
            ->once()
            ->with(
                ClassMemberTesterTestClass::class,
                'staticMethod1',
                $method,
                \Mockery::type('callable'),
                [],
                [],
                [],
                []
            );

        $this->classMemberTester->testStaticMethods(
            ClassMemberTesterTestClass::class,
            $passes,
            $failures,
            $skips,
            $warnings
        );
    }
}

class ClassMemberTesterTestClass
{
    public function instanceMethod1(): string
    {
        return 'instance1';
    }

    public function instanceMethod2(): string
    {
        return 'instance2';
    }

    public static function staticMethod1(): string
    {
        return 'static1';
    }

    public static function staticMethod2(): string
    {
        return 'static2';
    }
}
