<?php

/*
 * PHPSure
 * Copyright (c) Dan Phillimore (asmblah)
 * https://github.com/phpsure/phpsure/
 *
 * Released under the MIT license.
 * https://github.com/phpsure/phpsure/raw/main/MIT-LICENSE.txt
 */

declare(strict_types=1);

namespace PHPSure\Tests\Unit\Runner;

use Mockery\MockInterface;
use PHPSure\Attributes\Fixture;
use PHPSure\Generator\ArgumentResolverInterface;
use PHPSure\Generator\FixtureMaterialiserInterface;
use PHPSure\Generator\TokenGenerator;
use PHPSure\Runner\InstanceCreator;
use PHPSure\Runner\ScenarioManagerInterface;
use PHPSure\Tests\AbstractTestCase;
use RuntimeException;

/**
 * Class InstanceCreatorTest.
 *
 * @author Dan Phillimore <dan@ovms.co>
 */
class InstanceCreatorTest extends AbstractTestCase
{
    private MockInterface&ArgumentResolverInterface $argumentResolver;
    private MockInterface&FixtureMaterialiserInterface $fixtureMaterialiser;
    private InstanceCreator $instanceCreator;
    private MockInterface&ScenarioManagerInterface $scenarioManager;
    private MockInterface&TokenGenerator $tokenGenerator;

    public function setUp(): void
    {
        $this->scenarioManager = mock(ScenarioManagerInterface::class);
        $this->argumentResolver = mock(ArgumentResolverInterface::class);
        $this->fixtureMaterialiser = mock(FixtureMaterialiserInterface::class);
        $this->tokenGenerator = mock(TokenGenerator::class);
        $this->instanceCreator = new InstanceCreator(
            $this->scenarioManager,
            $this->argumentResolver,
            $this->fixtureMaterialiser,
            $this->tokenGenerator
        );
    }

    public function testCreateInstanceCreatesInstanceWithNoConstructor(): void
    {
        $wasAutoGenerated = false;

        $instance = $this->instanceCreator->createInstance(InstanceCreatorTestFixtureNoConstructor::class, $wasAutoGenerated);

        $this->assertInstanceOf(InstanceCreatorTestFixtureNoConstructor::class, $instance);
        $this->assertFalse($wasAutoGenerated);
    }

    public function testCreateInstanceCreatesInstanceWithPublicConstructorAndNoFixtures(): void
    {
        $wasAutoGenerated = false;

        // Multiple calls to getFixtures throughout the flow.
        $this->scenarioManager->allows('getFixtures')
            ->andReturn([]);

        $this->scenarioManager->allows('findFixtureByName')
            ->andReturn(null);

        $this->tokenGenerator->expects('generateForParameters')
            ->once()
            ->andReturn([42, 'test']);

        $instance = $this->instanceCreator->createInstance(InstanceCreatorTestFixturePublicConstructor::class, $wasAutoGenerated);

        $this->assertInstanceOf(InstanceCreatorTestFixturePublicConstructor::class, $instance);
        $this->assertTrue($wasAutoGenerated);
        $this->assertSame(42, $instance->value);
        $this->assertSame('test', $instance->name);
    }

    public function testCreateInstanceCreatesInstanceWithDefaultFixture(): void
    {
        $wasAutoGenerated = false;
        $defaultFixture = new Fixture(name: Fixture::DEFAULT_NAME, args: [100, 'default']);

        $this->scenarioManager->expects('getFixtures')
            ->once()
            ->andReturn([$defaultFixture]);

        $this->scenarioManager->expects('findFixtureByName')
            ->once()
            ->with([$defaultFixture], Fixture::DEFAULT_NAME)
            ->andReturn($defaultFixture);

        $this->argumentResolver->expects('resolveScenarioArguments')
            ->once()
            ->with([100, 'default'], $this->fixtureMaterialiser)
            ->andReturn([100, 'default']);

        $instance = $this->instanceCreator->createInstance(InstanceCreatorTestFixturePublicConstructor::class, $wasAutoGenerated);

        $this->assertInstanceOf(InstanceCreatorTestFixturePublicConstructor::class, $instance);
        $this->assertFalse($wasAutoGenerated);
        $this->assertSame(100, $instance->value);
        $this->assertSame('default', $instance->name);
    }

    public function testCreateInstanceCreatesInstanceWithFirstFixtureWhenNoDefault(): void
    {
        $wasAutoGenerated = false;
        $fixture1 = new Fixture(name: 'fixture1', args: [200, 'first']);
        $fixture2 = new Fixture(name: 'fixture2', args: [300, 'second']);

        // getFixtures will be called multiple times - always return the fixtures.
        $this->scenarioManager->allows('getFixtures')
            ->andReturn([$fixture1, $fixture2]);

        $this->scenarioManager->allows('findFixtureByName')
            ->andReturn(null);

        $this->argumentResolver->expects('resolveScenarioArguments')
            ->once()
            ->with([200, 'first'], $this->fixtureMaterialiser)
            ->andReturn([200, 'first']);

        $instance = $this->instanceCreator->createInstance(InstanceCreatorTestFixturePublicConstructor::class, $wasAutoGenerated);

        $this->assertInstanceOf(InstanceCreatorTestFixturePublicConstructor::class, $instance);
        $this->assertFalse($wasAutoGenerated);
        $this->assertSame(200, $instance->value);
        $this->assertSame('first', $instance->name);
    }

    public function testCreateInstanceReturnsNullForPrivateConstructorWithNoFixtures(): void
    {
        $wasAutoGenerated = false;

        // Multiple calls to getFixtures.
        $this->scenarioManager->allows('getFixtures')
            ->andReturn([]);

        $this->scenarioManager->allows('findFixtureByName')
            ->andReturn(null);

        $instance = $this->instanceCreator->createInstance(InstanceCreatorTestFixturePrivateConstructor::class, $wasAutoGenerated);

        $this->assertNull($instance);
        $this->assertFalse($wasAutoGenerated);
    }

    public function testCreateInstanceForFixtureCreatesInstanceWithSpecificFixture(): void
    {
        $wasAutoGenerated = false;
        $fixture1 = new Fixture(name: 'fixture1', args: [111, 'one']);
        $fixture2 = new Fixture(name: 'fixture2', args: [222, 'two']);

        $this->scenarioManager->expects('getFixtures')
            ->once()
            ->andReturn([$fixture1, $fixture2]);

        $this->scenarioManager->expects('findFixtureByName')
            ->once()
            ->with([$fixture1, $fixture2], 'fixture2')
            ->andReturn($fixture2);

        $this->argumentResolver->expects('resolveScenarioArguments')
            ->once()
            ->with([222, 'two'], $this->fixtureMaterialiser)
            ->andReturn([222, 'two']);

        $instance = $this->instanceCreator->createInstanceForFixture(
            InstanceCreatorTestFixturePublicConstructor::class,
            'fixture2',
            $wasAutoGenerated
        );

        $this->assertInstanceOf(InstanceCreatorTestFixturePublicConstructor::class, $instance);
        $this->assertFalse($wasAutoGenerated);
        $this->assertSame(222, $instance->value);
        $this->assertSame('two', $instance->name);
    }

    public function testCreateInstanceForFixtureReturnsNullWhenFixtureNotFound(): void
    {
        $wasAutoGenerated = false;
        $fixture1 = new Fixture(name: 'fixture1', args: [111, 'one']);

        // getFixtures will be called multiple times - always return the same fixtures.
        $this->scenarioManager->allows('getFixtures')
            ->andReturn([$fixture1]);

        $this->scenarioManager->allows('findFixtureByName')
            ->andReturn(null);

        $instance = $this->instanceCreator->createInstanceForFixture(
            InstanceCreatorTestFixturePublicConstructor::class,
            'nonexistent',
            $wasAutoGenerated
        );

        $this->assertNull($instance);
        $this->assertFalse($wasAutoGenerated);
    }

    public function testCreateInstanceUsesStaticFactoryMethodWithDefaultFixture(): void
    {
        $wasAutoGenerated = false;
        $defaultFixture = new Fixture(name: Fixture::DEFAULT_NAME, args: [999]);

        $this->scenarioManager->expects('getFixtures')
            ->twice()
            ->andReturn([], [$defaultFixture]);

        $this->scenarioManager->expects('findFixtureByName')
            ->once()
            ->with([$defaultFixture], Fixture::DEFAULT_NAME)
            ->andReturn($defaultFixture);

        $this->argumentResolver->expects('resolveScenarioArguments')
            ->once()
            ->with([999], $this->fixtureMaterialiser)
            ->andReturn([999]);

        $instance = $this->instanceCreator->createInstance(InstanceCreatorTestFixtureWithFactory::class, $wasAutoGenerated);

        $this->assertInstanceOf(InstanceCreatorTestFixtureWithFactory::class, $instance);
        $this->assertFalse($wasAutoGenerated);
        $this->assertSame(999, $instance->value);
    }

    public function testCreateInstanceUsesStaticFactoryMethodWithSpecificFixture(): void
    {
        $wasAutoGenerated = false;
        $fixture1 = new Fixture(name: 'factory1', args: [777]);
        $fixture2 = new Fixture(name: 'factory2', args: [888]);

        $this->scenarioManager->expects('getFixtures')
            ->twice()
            ->andReturn([], [$fixture1, $fixture2]);

        $this->scenarioManager->expects('findFixtureByName')
            ->once()
            ->with([$fixture1, $fixture2], 'factory2')
            ->andReturn($fixture2);

        $this->argumentResolver->expects('resolveScenarioArguments')
            ->once()
            ->with([888], $this->fixtureMaterialiser)
            ->andReturn([888]);

        $instance = $this->instanceCreator->createInstanceForFixture(
            InstanceCreatorTestFixtureWithFactory::class,
            'factory2',
            $wasAutoGenerated
        );

        $this->assertInstanceOf(InstanceCreatorTestFixtureWithFactory::class, $instance);
        $this->assertFalse($wasAutoGenerated);
        $this->assertSame(888, $instance->value);
    }

    public function testCreateInstanceAutoGeneratesUsingStaticFactoryMethod(): void
    {
        $wasAutoGenerated = false;

        // Multiple calls to getFixtures for constructor and factory methods.
        $this->scenarioManager->allows('getFixtures')
            ->andReturn([]);

        $this->scenarioManager->allows('findFixtureByName')
            ->andReturn(null);

        $this->tokenGenerator->expects('generateForParameters')
            ->once()
            ->andReturn([555]);

        $instance = $this->instanceCreator->createInstance(InstanceCreatorTestFixtureWithFactory::class, $wasAutoGenerated);

        $this->assertInstanceOf(InstanceCreatorTestFixtureWithFactory::class, $instance);
        $this->assertTrue($wasAutoGenerated);
        $this->assertSame(555, $instance->value);
    }

    public function testCreateInstanceReturnsNullWhenAutoGenerationFails(): void
    {
        $wasAutoGenerated = false;

        // Multiple calls to getFixtures.
        $this->scenarioManager->allows('getFixtures')
            ->andReturn([]);

        $this->scenarioManager->allows('findFixtureByName')
            ->andReturn(null);

        $this->tokenGenerator->expects('generateForParameters')
            ->once()
            ->andThrow(new RuntimeException('Cannot generate'));

        $instance = $this->instanceCreator->createInstance(InstanceCreatorTestFixturePublicConstructor::class, $wasAutoGenerated);

        $this->assertNull($instance);
        $this->assertFalse($wasAutoGenerated);
    }
}

/**
 * Fixture class with no constructor.
 */
class InstanceCreatorTestFixtureNoConstructor
{
}

/**
 * Fixture class with public constructor.
 */
class InstanceCreatorTestFixturePublicConstructor
{
    public function __construct(
        public int $value,
        public string $name
    ) {
    }
}

/**
 * Fixture class with private constructor.
 */
class InstanceCreatorTestFixturePrivateConstructor
{
    private function __construct()
    {
    }
}

/**
 * Fixture class with static factory method.
 */
class InstanceCreatorTestFixtureWithFactory
{
    public function __construct(
        public int $value
    ) {
    }

    public static function create(int $value): self
    {
        return new self($value);
    }
}
