<?php

/*
 * PHPSure
 * Copyright (c) Dan Phillimore (asmblah)
 * https://github.com/phpsure/phpsure/
 *
 * Released under the MIT license.
 * https://github.com/phpsure/phpsure/raw/main/MIT-LICENSE.txt
 */

declare(strict_types=1);

namespace PHPSure\Runner;

use PHPSure\Runner\Result\FailResult;
use PHPSure\Runner\Result\PassResult;
use PHPSure\Runner\Result\SkipResult;
use PHPSure\Runner\Result\WarningResult;
use ReflectionException;

/**
 * Interface ClassMemberTesterInterface.
 *
 * Tests instance and static methods of classes.
 *
 * @author Dan Phillimore <dan@ovms.co>
 */
interface ClassMemberTesterInterface
{
    /**
     * Tests instance methods of a class.
     *
     * @param string $className The class name.
     * @param object|null $instance The instance to test, or null if no default instance exists.
     * @param bool $instanceWasAutoGenerated Whether the instance was auto-generated.
     * @param array<PassResult> &$passes Output parameter for pass results.
     * @param array<FailResult> &$failures Output parameter for fail results.
     * @param array<SkipResult> &$skips Output parameter for skip results.
     * @param array<WarningResult> &$warnings Output parameter for warning results.
     * @throws ReflectionException When the class cannot be reflected.
     */
    public function testInstanceMethods(
        string $className,
        ?object $instance,
        bool $instanceWasAutoGenerated,
        array &$passes,
        array &$failures,
        array &$skips,
        array &$warnings
    ): void;

    /**
     * Tests static methods of a class.
     *
     * @param string $className The class name.
     * @param array<PassResult> &$passes Output parameter for pass results.
     * @param array<FailResult> &$failures Output parameter for fail results.
     * @param array<SkipResult> &$skips Output parameter for skip results.
     * @param array<WarningResult> &$warnings Output parameter for warning results.
     * @throws ReflectionException When the class cannot be reflected.
     */
    public function testStaticMethods(
        string $className,
        array &$passes,
        array &$failures,
        array &$skips,
        array &$warnings
    ): void;
}
