<?php

/*
 * PHPSure
 * Copyright (c) Dan Phillimore (asmblah)
 * https://github.com/phpsure/phpsure/
 *
 * Released under the MIT license.
 * https://github.com/phpsure/phpsure/raw/main/MIT-LICENSE.txt
 */

declare(strict_types=1);

namespace PHPSure\Runner;

use PHPSure\Discovery\Scanner;
use PHPSure\Generator\TokenGenerator;
use PHPSure\Runner\Result\FailResult;
use PHPSure\Runner\Result\PassResult;
use PHPSure\Runner\Result\SkipResult;
use PHPSure\Runner\Result\WarningResult;
use ReflectionException;

/**
 * Class ClassMemberTester.
 *
 * Tests instance and static methods of classes.
 *
 * @author Dan Phillimore <dan@ovms.co>
 */
class ClassMemberTester implements ClassMemberTesterInterface
{
    public function __construct(
        private readonly Scanner $scanner,
        private readonly TokenGenerator $tokenGenerator,
        private readonly MethodTesterInterface $methodTester
    ) {
    }

    /**
     * Tests instance methods of a class.
     *
     * @param string $className The class name.
     * @param object|null $instance The instance to test, or null if no default instance exists.
     * @param bool $instanceWasAutoGenerated Whether the instance was auto-generated.
     * @param array<PassResult> &$passes Output parameter for pass results.
     * @param array<FailResult> &$failures Output parameter for fail results.
     * @param array<SkipResult> &$skips Output parameter for skip results.
     * @param array<WarningResult> &$warnings Output parameter for warning results.
     * @throws ReflectionException When the class cannot be reflected.
     */
    public function testInstanceMethods(
        string $className,
        ?object $instance,
        bool $instanceWasAutoGenerated,
        array &$passes,
        array &$failures,
        array &$skips,
        array &$warnings
    ): void {
        $methods = $this->scanner->getInstanceMethods($className);

        foreach ($methods as $methodName => $method) {
            $this->methodTester->testInstanceMethod(
                $className,
                $methodName,
                $method,
                fn () => $method->invoke($instance, ...$this->tokenGenerator->generateForParameters($method)),
                $instance,
                $instanceWasAutoGenerated,
                $passes,
                $failures,
                $skips,
                $warnings
            );
        }
    }

    /**
     * Tests static methods of a class.
     *
     * @param string $className The class name.
     * @param array<PassResult> &$passes Output parameter for pass results.
     * @param array<FailResult> &$failures Output parameter for fail results.
     * @param array<SkipResult> &$skips Output parameter for skip results.
     * @param array<WarningResult> &$warnings Output parameter for warning results.
     * @throws ReflectionException When the class cannot be reflected.
     */
    public function testStaticMethods(
        string $className,
        array &$passes,
        array &$failures,
        array &$skips,
        array &$warnings
    ): void {
        $methods = $this->scanner->getStaticMethods($className);

        foreach ($methods as $methodName => $method) {
            $this->methodTester->testStaticMethod(
                $className,
                $methodName,
                $method,
                fn () => $method->invoke(null, ...$this->tokenGenerator->generateForParameters($method)),
                $passes,
                $failures,
                $skips,
                $warnings
            );
        }
    }
}
