<?php

/*
 * PHPSure
 * Copyright (c) Dan Phillimore (asmblah)
 * https://github.com/phpsure/phpsure/
 *
 * Released under the MIT license.
 * https://github.com/phpsure/phpsure/raw/main/MIT-LICENSE.txt
 */

declare(strict_types=1);

namespace PHPSure\Runner;

use PHPSure\Discovery\DiscoveryResultInterface;
use PHPSure\Runner\Result\FailResult;
use PHPSure\Runner\Result\PassResult;
use PHPSure\Runner\Result\SkipResult;
use PHPSure\Runner\Result\WarningResult;
use ReflectionClass;
use ReflectionException;
use Throwable;

/**
 * Class ClassTester.
 *
 * Tests classes.
 *
 * @author Dan Phillimore <dan@ovms.co>
 */
class ClassTester implements ClassTesterInterface
{
    public function __construct(
        private readonly InstanceCreatorInterface $instanceCreator,
        private readonly ClassMemberTesterInterface $classMemberTester
    ) {
    }

    /**
     * Tests all discovered classes.
     *
     * @param DiscoveryResultInterface $discoveryResult The result of scanning for classes.
     * @param array<PassResult> &$passes Output parameter for pass results.
     * @param array<FailResult> &$failures Output parameter for fail results.
     * @param array<SkipResult> &$skips Output parameter for skip results.
     * @param array<WarningResult> &$warnings Output parameter for warning results.
     * @throws ReflectionException When a class cannot be reflected.
     */
    public function testClasses(
        DiscoveryResultInterface $discoveryResult,
        array &$passes,
        array &$failures,
        array &$skips,
        array &$warnings
    ): void {
        foreach ($discoveryResult->getClassNames() as $className) {
            try {
                $class = new ReflectionClass($className);

                if ($class->isAbstract() || $class->isInterface()) {
                    // TODO: Support defining scenarios on interface and abstract methods
                    //       to allow enforcing the interface contract.
                    continue;
                }

                $wasAutoGenerated = false;
                $instance = $this->instanceCreator->createInstance($className, $wasAutoGenerated);

                // Always test instance methods - they may have scenarios that create their own instances.
                $this->classMemberTester->testInstanceMethods($className, $instance, $wasAutoGenerated, $passes, $failures, $skips, $warnings);

                $this->classMemberTester->testStaticMethods($className, $passes, $failures, $skips, $warnings);
            } catch (Throwable $e) {
                $skips[] = new SkipResult('Class ' . $className, $e->getMessage());
            }
        }
    }
}
