<?php

/*
 * PHPSure
 * Copyright (c) Dan Phillimore (asmblah)
 * https://github.com/phpsure/phpsure/
 *
 * Released under the MIT license.
 * https://github.com/phpsure/phpsure/raw/main/MIT-LICENSE.txt
 */

declare(strict_types=1);

namespace PHPSure\Runner;

use ReflectionException;

/**
 * Interface InstanceCreatorInterface.
 *
 * Creates instances of classes using fixtures or auto-generation.
 *
 * @author Dan Phillimore <dan@ovms.co>
 */
interface InstanceCreatorInterface
{
    /**
     * Creates an instance of a class using fixture/ctor rules.
     *
     * @param string $className The class name.
     * @param bool &$wasAutoGenerated Output parameter indicating if the instance was auto-generated.
     * @return object|null The instance, or null if it could not be created.
     * @throws ReflectionException When the class cannot be reflected.
     */
    public function createInstance(string $className, bool &$wasAutoGenerated = false): ?object;

    /**
     * Creates an instance of a class using a specific constructor fixture.
     *
     * @param string $className The class name.
     * @param string|null $fixtureName The name of the constructor fixture to use, or null for default behavior.
     * @param bool &$wasAutoGenerated Output parameter indicating if the instance was auto-generated.
     * @return object|null The instance, or null if it could not be created.
     * @throws ReflectionException When the class cannot be reflected.
     */
    public function createInstanceForFixture(string $className, ?string $fixtureName, bool &$wasAutoGenerated = false): ?object;
}
