<?php

/*
 * PHPSure
 * Copyright (c) Dan Phillimore (asmblah)
 * https://github.com/phpsure/phpsure/
 *
 * Released under the MIT license.
 * https://github.com/phpsure/phpsure/raw/main/MIT-LICENSE.txt
 */

declare(strict_types=1);

namespace PHPSure\Runner;

use PHPSure\Runner\Result\FailResult;
use PHPSure\Runner\Result\PassResult;
use PHPSure\Runner\Result\SkipResult;
use PHPSure\Runner\Result\WarningResult;
use ReflectionMethod;

/**
 * Interface MethodTesterInterface.
 *
 * Tests individual methods.
 *
 * @author Dan Phillimore <dan@ovms.co>
 */
interface MethodTesterInterface
{
    /**
     * Tests an instance method with optional scenario-based expect checks.
     *
     * @param string $className The class name.
     * @param string $methodName The method name.
     * @param ReflectionMethod $method The method reflection.
     * @param callable $invoker Callable that invokes the method and returns the result.
     * @param object|null $instance The instance to use for instance methods.
     * @param bool $instanceWasAutoGenerated Whether the instance was auto-generated.
     * @param array<PassResult> &$passes Output parameter for pass results.
     * @param array<FailResult> &$failures Output parameter for fail results.
     * @param array<SkipResult> &$skips Output parameter for skip results.
     * @param array<WarningResult> &$warnings Output parameter for warning results.
     */
    public function testInstanceMethod(
        string $className,
        string $methodName,
        ReflectionMethod $method,
        callable $invoker,
        ?object $instance,
        bool $instanceWasAutoGenerated,
        array &$passes,
        array &$failures,
        array &$skips,
        array &$warnings
    ): void;

    /**
     * Tests a static method with optional scenario-based expect checks.
     *
     * @param string $className The class name.
     * @param string $methodName The method name.
     * @param ReflectionMethod $method The method reflection.
     * @param callable $invoker Callable that invokes the method and returns the result.
     * @param array<PassResult> &$passes Output parameter for pass results.
     * @param array<FailResult> &$failures Output parameter for fail results.
     * @param array<SkipResult> &$skips Output parameter for skip results.
     * @param array<WarningResult> &$warnings Output parameter for warning results.
     */
    public function testStaticMethod(
        string $className,
        string $methodName,
        ReflectionMethod $method,
        callable $invoker,
        array &$passes,
        array &$failures,
        array &$skips,
        array &$warnings
    ): void;
}
